language: python
dist: xenial
os: linux
cache:
  pip: true
  directories:
    - $HOME/buildout-cache

jobs:
    include:
        - python: "3.6"
          env: TOXENV=py36,lint-py36
        - python: "3.7"
          env: TOXENV=py37,lint-py37
        - python: "3.8"
          env: TOXENV=py38,lint-py38

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    travis_retry pip3 install -U tox-travis coveralls coverage

# command to run tests, e.g. python setup.py test
script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls
