[project]
name = "plonecli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bobtemplates.plone>=7.0.0a4",
    "Click>=7.0",
    "click-aliases",
    "mr.bob",
    "tox",
]
